### ISSUE TITLE
Configure mergify

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/python-can#821]
I've enabled [Mergify](https://mergify.io/) on this repository but haven't yet decided how we should configure it.

I'm thinking something like this:

```
pull_request_rules:
  - name: Automatic merge on up to date branch with dual approval
    conditions:
      - "#approved-reviews-by>=2"
      - "status-success=continuous-integration/travis-ci/pr"
      - "label!=work-in-progress"
    actions:
      merge:
        method: merge
        strict: true
```

This would mean any travis passing PR that has two approvals would get automatically merged. We can lower the bar to one approval after we are happy it appears to be working.

Configuration docs [here](https://doc.mergify.io/configuration.html).
